# Generated by Django 5.2.1 on 2025-05-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
